__title__ = 'xmind2csv'
__description__ = 'XMind2csv基于Python实现，提供了一个高效测试用例设计的解决方案！'
__keywords__ = 'xmind2testCase, testcase, test, testing, xmind, 思维导图, 禅道, 测试用例',
__url__ = 'https://github.com/laolyu/xmind2csv'
__author__ = 'York'
__author_email__ = '1300203001@qq.com'
__version__ = '1.6.1'
__license__ = 'MIT'
__cake__ = u'\u2728 \U0001f370 \u2728'
